[project]
name = "lx-ai"
revision = "1.0"

[profiles.default]
HOME_DIR = { default = "." }
WORKING_DIR = { default = "." }
DATA_DIR = { default = "data" }
CONF_DIR = { default = "conf" }

FRAME_DIR = { default = "{DATA_DIR}/frames" }

DJANGO_ENV = { default = "development" }
DJANGO_DEBUG = { default = "True" }

DJANGO_SETTINGS_MODULE = { default = "lx_ai.settings.settings_dev" }
DJANGO_SETTINGS_MODULE_DEVELOPMENT = { default = "lx_ai.settings.settings_dev" }
DJANGO_SETTINGS_MODULE_PRODUCTION = { default = "lx_ai.settings.settings_prod" }

DJANGO_DB_ENGINE = { default = "django.db.backends.postgresql" }
DJANGO_DB_HOST = { default = "localhost" }
DJANGO_DB_PORT = { default = "5432" }
DJANGO_DB_NAME = { default = "endoregDbLocal" }
DJANGO_DB_USER = { default = "endoregDbLocal" }
DJANGO_DB_PASSWORD_FILE = { default = "{CONF_DIR}/db_pwd" }
DJANGO_DB_SSLMODE = { default = "prefer" }

LOG_LEVEL = { default = "INFO" }

[profiles.development]
DJANGO_ENV = { default = "development" }
DJANGO_DEBUG = { default = "True" }
DJANGO_SETTINGS_MODULE = { default = "lx_ai.settings.settings_dev" }
LOG_LEVEL = { default = "DEBUG" }

[profiles.production]
DJANGO_ENV = { default = "production" }
DJANGO_DEBUG = { default = "False" }
DJANGO_SETTINGS_MODULE = { default = "lx_ai.settings.settings_prod" }
LOG_LEVEL = { default = "INFO" }