dataset_uuid: sandbox_ds

# ------------------------------
# DATA SOURCE
# ------------------------------
data_source: postgres

dataset_ids:
  - 1  # Even if it's just one, it should be wrapped in a list
  #- 2  # Uncomment for multiple dataset IDs


labelset_id: 2
labelset_version_to_train: 2

# EXACT endoreg-db semantics:
# false → ignore unknowns (None)
# true  → treat unknown as negative (0)
treat_unlabeled_as_negative: true

# ------------------------------
# MODEL
# Model options:
# ------------------------------
backbone_name: gastro_rn50
backbone_checkpoint: /home/admin/dev/lx-ai/data/model_training/checkpoints/RN50_GastroNet-1M_DINOv1.pth
freeze_backbone: true

# ------------------------------
# TRAINING
# ------------------------------
num_epochs: 20
batch_size: 16

# Data Split Configuration
val_split: 0.1  # 10% for validation
test_split: 0.1  # 10% for testing

# Specify number of buckets (for splitting data)
num_buckets: 4  # Four buckets

# Bucket IDs for each data role
train_bucket_ids:
  - 0
  - 1
  - 2  # Assigning 3 buckets for training
val_bucket_ids:
  - 3  # 1 bucket for validation
test_bucket_ids:
  - 4  # 1 bucket for testing (could adjust as per your split)

# Learning Rate Configuration
lr_head: 0.001
lr_backbone: 0.0001
gamma_focal: 2.0
alpha_focal: 0.25

use_scheduler: true
warmup_epochs: 2
min_lr: 1.0e-6

device: cuda
random_seed: 42
